import csv


data = [
    ['I love this product', 'positive'],
    ['This is a great movie', 'positive'],
    ['The food was delicious', 'positive'],
    ['The service was terrible', 'negative'],
    ['I did not like the book', 'negative'],
    ['The performance was disappointing', 'negative'],
    ['The weather is beautiful today', 'neutral'],
    ['I had a good time at the party', 'positive'],
    ['The customer support was helpful', 'positive'],
    ['The price is too high', 'negative'],
    ['The quality of the product is excellent', 'positive'],
    ['I found the article informative', 'positive'],
    ['The traffic was awful this morning', 'negative'],
    ['The new feature is impressive', 'positive'],
    ['I received a defective item', 'negative'],
    ['The hotel room was clean and comfortable', 'positive'],
    ['The movie plot was confusing', 'negative'],
    ['The game ended in a tie', 'neutral'],
    ['The performance was outstanding', 'positive'],
    ['The software crashed multiple times', 'negative'],
    ['The service was slow', 'negative'],
    ['The music was soothing', 'positive'],
    ['The product is not user-friendly', 'negative'],
    ['The presentation was engaging', 'positive'],
    ['The experience was underwhelming', 'negative'],
    ['The package arrived on time', 'positive'],
    ['The design is visually appealing', 'positive'],
    ['The taste of the dish was bland', 'negative'],
    ['The event was well-organized', 'positive'],
    ['The company''s response was prompt', 'positive'],
    ['The results were inconclusive', 'neutral'],
    ['The communication was clear and concise', 'positive'],
    ['The performance was mediocre', 'neutral'],
    ['The application is prone to crashes', 'negative'],
    ['The atmosphere was cozy', 'positive'],
    ['The battery life is impressive', 'positive'],
    ['The presentation lacked substance', 'negative'],
    ['The team played exceptionally well', 'positive'],
    ['The website is difficult to navigate', 'negative'],
    ['The product arrived damaged', 'negative'],
    ['The experience was unforgettable', 'positive'],
    ['The movie was a box office success', 'positive'],
    ['The service exceeded my expectations', 'positive'],
    ['The noise level was unbearable', 'negative'],
    ['The results were disappointing', 'negative'],
    ['The interface is intuitive', 'positive'],
    ['The book received rave reviews', 'positive'],
    ['The customer service was unhelpful', 'negative'],
    ['The conversation was engaging', 'positive'],
    ['The software is outdated', 'negative'],
    ['The performance was mesmerizing', 'positive'],
    ['The product is overpriced', 'negative'],
    ['The experience was lackluster', 'negative'],
    ['The atmosphere was vibrant', 'positive'],
    ['The device is user-friendly', 'positive'],
    ['The presentation was uninspiring', 'negative'],
    ['The team''s effort was commendable', 'positive'],
    ['The website has a slow loading speed', 'negative'],
    ['The quality of the service is top-notch', 'positive'],
    ['The results were inconclusive', 'neutral'],
    ['The application is not user-friendly', 'negative'],
    ['The concert was sold out', 'positive'],
    ['The performance was lackluster', 'negative'],
    ['The food was tasteless', 'negative'],
    ['The event was poorly organized', 'negative'],
    ['The software has a steep learning curve', 'negative'],
    ['The experience was magical', 'positive'],
    ['The movie has received mixed reviews', 'neutral'],
    ['The service fell short of expectations', 'negative'],
    ['The conversation was dull', 'negative'],
    ['The product lacks durability', 'negative'],
    ['The performance was exceptional', 'positive'],
    ['The price is reasonable', 'positive'],
    ['The experience was uneventful', 'neutral'],
    ['The website layout is confusing', 'negative'],
    ['The quality of the product is subpar', 'negative'],
    ['The movie had a predictable plot', 'negative'],
    ['The customer support was unresponsive', 'negative'],
    ['The conversation was stimulating', 'positive'],
    ['The software needs improvement', 'negative'],
    ['The performance was breathtaking', 'positive'],
    ['The product is worth the investment', 'positive'],
    ['The experience was disappointing', 'negative'],
    ['The atmosphere was energetic', 'positive'],
    ['The device is technologically advanced', 'positive'],
    ['The presentation was captivating', 'positive'],
    ['The team''s performance was lackluster', 'negative'],
    ['The website is poorly designed', 'negative'],
    ['The product is of high quality', 'positive'],
    ['The results were inconclusive', 'neutral'],
    ['The application is slow', 'negative'],
    ['The concert was a huge success', 'positive'],
    ['The performance was subpar', 'negative'],
    ['The food was exquisite', 'positive'],
    ['The event was a disaster', 'negative'],
    ['The software is user-friendly', 'positive']
]


# Specify the column names
header = ['text', 'tags']

# Specify the file path to save the CSV file
file_path = 'data.csv'

# Write the data to the CSV file
with open(file_path, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(header)  # Write the header
    writer.writerows(data)   # Write the data rows

print(f"Data CSV file generated successfully at: {file_path}")